package vista;

import controlador.ControladorProducto;
import javax.swing.JButton;
import javax.swing.JFormattedTextField;
import javax.swing.JTable;
import javax.swing.JTextField;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author desaextremo
 */
public class Tienda extends javax.swing.JFrame {
    private ControladorProducto controlador;

    /**
     * Creates new form RetoTrs
     */
    public Tienda() {
        initComponents();
        this.setVisible(true);
    }
    
    /**
     * 
     * @return 
     */
    public JButton getBotonAgregarProducto() {
        return botonAgregarProducto;
    }

    /**
     * 
     * @return 
     */
    public JButton getBotonActualizarProducto() {
        return botonActualizar;
    }

    /**
     * 
     * @return 
     */
    public JButton getBotonBorrarProducto() {
        return botonBorrar;
    }

    /**
     * 
     * @return 
     */
    public JButton getBotonInformes() {
        return botonInformes;
    }
    
    /**
     * 
     * @return 
     */
    public JTextField getCajaNombre() {
        return cajaNombre;
    }
    
    /**
     * 
     * @return 
     */
    public JFormattedTextField getCajaPrecio() {
        return cajaPrecio;
    }
    
    /**
     * 
     * @return 
     */
    public JFormattedTextField getCajaInventario() {
        return cajaInventario;
    }
    
    /**
     * 
     * @return 
     */
    public JTextField getCajaCodigo() {
        return cajaCodigo;
    }
    
    /**
     * 
     * @return 
     */
    public JTable getTablaDatos() {
        return tablaProductos;
    }
   
    /**
     * 
     * @param controlador 
     */
    public void setControlador(ControladorProducto controlador) {
        this.controlador = controlador;
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelNuevoProducto = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        botonAgregarProducto = new javax.swing.JButton();
        cajaPrecio = new javax.swing.JFormattedTextField();
        cajaNombre = new javax.swing.JTextField();
        cajaInventario = new javax.swing.JFormattedTextField();
        cajaCodigo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        panelListarProductos = new javax.swing.JScrollPane();
        tablaProductos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        panaelBotones = new javax.swing.JPanel();
        botonBorrar = new javax.swing.JButton();
        botonActualizar = new javax.swing.JButton();
        botonInformes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelNuevoProducto.setBorder(javax.swing.BorderFactory.createTitledBorder("Agregar Nuevo Producto"));

        jLabel2.setText("Nombre:");

        jLabel3.setText("Precio:");

        jLabel4.setText("Inventario:");

        botonAgregarProducto.setText("Agregar Producto");
        botonAgregarProducto.setToolTipText("");

        cajaCodigo.setEditable(false);
        cajaCodigo.setBackground(new java.awt.Color(204, 255, 255));

        jLabel5.setText("Id:");

        javax.swing.GroupLayout panelNuevoProductoLayout = new javax.swing.GroupLayout(panelNuevoProducto);
        panelNuevoProducto.setLayout(panelNuevoProductoLayout);
        panelNuevoProductoLayout.setHorizontalGroup(
            panelNuevoProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNuevoProductoLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(panelNuevoProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNuevoProductoLayout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addComponent(botonAgregarProducto, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                        .addGap(230, 230, 230))
                    .addGroup(panelNuevoProductoLayout.createSequentialGroup()
                        .addGroup(panelNuevoProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5))
                        .addGap(24, 24, 24)
                        .addGroup(panelNuevoProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cajaPrecio)
                            .addComponent(cajaInventario)
                            .addComponent(cajaNombre)
                            .addComponent(cajaCodigo))))
                .addGap(28, 28, 28))
        );
        panelNuevoProductoLayout.setVerticalGroup(
            panelNuevoProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNuevoProductoLayout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(panelNuevoProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cajaCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelNuevoProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cajaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelNuevoProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cajaPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelNuevoProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cajaInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonAgregarProducto)
                .addContainerGap())
        );

        panelNuevoProductoLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cajaCodigo, cajaInventario, cajaNombre, cajaPrecio});

        panelListarProductos.setBorder(javax.swing.BorderFactory.createTitledBorder("Listado de Productos"));

        tablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tablaProductos.setSelectionBackground(java.awt.SystemColor.activeCaption);
        tablaProductos.setSelectionForeground(new java.awt.Color(255, 255, 255));
        panelListarProductos.setViewportView(tablaProductos);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Bienvenido a la APP de Inventario");

        botonBorrar.setText("Borrar Producto");

        botonActualizar.setText("Actualizar Producto");

        botonInformes.setText("Informes");

        javax.swing.GroupLayout panaelBotonesLayout = new javax.swing.GroupLayout(panaelBotones);
        panaelBotones.setLayout(panaelBotonesLayout);
        panaelBotonesLayout.setHorizontalGroup(
            panaelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panaelBotonesLayout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(botonActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonBorrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonInformes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(107, 107, 107))
        );
        panaelBotonesLayout.setVerticalGroup(
            panaelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panaelBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panaelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonBorrar)
                    .addComponent(botonActualizar)
                    .addComponent(botonInformes))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panaelBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelNuevoProducto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelListarProductos))
                .addGap(70, 70, 70))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(panelNuevoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelListarProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panaelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonActualizar;
    private javax.swing.JButton botonAgregarProducto;
    private javax.swing.JButton botonBorrar;
    private javax.swing.JButton botonInformes;
    private javax.swing.JTextField cajaCodigo;
    private javax.swing.JFormattedTextField cajaInventario;
    private javax.swing.JTextField cajaNombre;
    private javax.swing.JFormattedTextField cajaPrecio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel panaelBotones;
    private javax.swing.JScrollPane panelListarProductos;
    private javax.swing.JPanel panelNuevoProducto;
    private javax.swing.JTable tablaProductos;
    // End of variables declaration//GEN-END:variables
}
